#! /bin/bash

runner='heroku'

if [ $FOREMAN ];
    then
        runner='foreman';
fi;
$runner run python manage.py initialise_databases && \
$runner run python manage.py load_mp_twirps_to_database && \
$runner run python manage.py subscribe_all_twirps_to_twitter 
